language: node_js
node_js:
- 10
branches:
  only:
  - master
install:
  - yarn --ignore-engines
script: 
  - yarn add travis-up
deploy:
  provider: script
  script: ./bin/up depoy production
  skip_cleanup: true
after_success:
  - ./bin/up url

env:
  global:
    AWS_REGION: us-west-1